services:
  gate:
    build:
      context: .
    ports: 
      - 3000:3000
    environment:
      - "NUCLEAR_STORES=store"
    command: node gate/gate.js

  store:
    deploy: 
      replicas: 3
    build:
      context: .
    command: node store/store.js