services:
  gate:
    build:
      context: .
    ports: 
      - 3000:3000
    volumes:
      - ./:/app:ro
    environment:
      - "NUCLEAR_STORES=store"
    command: nodemon gate/gate.js

  store:
    deploy: 
      replicas: 1
    build:
      context: .
    volumes:
      - ./:/app:ro
    command: nodemon store/store.js