version: "3.7"

services:
  <%#IS_PROD%>
  api:
    image: quay.io/containeros/api:latest
    networks:
      - containeros-system
      - caddy
    deploy:
      labels:
        caddy: <%API_HOST%>
        caddy.reverse_proxy: "{{upstreams 8080}}"
      placement:
        constraints:
          - "node.role==manager"
    secrets:
      - root_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
      - /root/.docker/:/root/.docker/

  node-setup:
    image: quay.io/containeros/node-setup
    networks:
      - containeros-system
    deploy:
      mode: global
    secrets:
      - root_token
    environment:
      - API_HOST=<%API_HOST%>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/:/root/.docker/
  <%/IS_PROD%>

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  registry: 
    image: registry:2
    networks:
      - containeros-system
    <%#IS_DEV%>
    ports:
      - 5000:5000
      - 5001:5001
    <%/IS_DEV%>
    environment:
      REGISTRY_STORAGE_S3_ACCESSKEY: <%REGISTRY_STORAGE_S3_ACCESSKEY%>
      REGISTRY_STORAGE_S3_SECRETKEY: <%REGISTRY_STORAGE_S3_SECRETKEY%>
      REGISTRY_STORAGE_S3_BUCKET: <%REGISTRY_STORAGE_S3_BUCKET%>
      REGISTRY_STORAGE_S3_REGIONENDPOINT: <%REGISTRY_STORAGE_S3_REGIONENDPOINT%>
      REGISTRY_STORAGE_S3_REGION: <%REGISTRY_STORAGE_S3_REGION%>
      REGISTRY_HTTP_ADDR: "0.0.0.0:5000"
      REGISTRY_STORAGE: s3
      REGISTRY_HTTP_DEBUG_ADDR: "0.0.0.0:5001"

  krakenkv:
    <%#IS_DEV%>
    ports:
      - 3000:3000
    <%/IS_DEV%>
    environment:
      - "KRAKENKV_STORES=krakenkv-store"
    image: quay.io/containeros/krakenkv-gate:1.0.0
    networks:
      - containeros-system

  krakenkv-store:
    image: quay.io/containeros/krakenkv-store:1.0.0
    networks:
      - containeros-system
    deploy:
      replicas: 1

networks:
  containeros-system:
  caddy:
    external: true

volumes:
  caddy_data: {}


secrets:
  root_token:
    external: true