# A simple example. See reference.yml for explanation for explanation of all options.
#
#  auth:
#    token:
#      realm: "http://127.0.0.1:5001/auth"
#      service: "Docker registry"
#      issuer: "Acme auth server"
#      rootcertbundle: "/path/to/server.pem"

server:
  addr: ":5001"
  certificate: "/dummy_certs/dummy_cert.pem"
  key: "/dummy_certs/dummy_key.key"

token:
  issuer: "Acme auth server"  # Must match issuer in the Registry config.
  expiration: 900

ext_auth:
  command: "/auth.js" 

acl:
  - match: {account: "root"}
    actions: ["pull"]
    comment: "root has pull access to everything. No push though"
  - match: {account: "/.+/", name: "${account}/*"}
    actions: ["*"]
    comment: "Logged in users have full access to images that are in their 'namespace'"