FROM cesanta/docker_auth:latest  
COPY ./docker_auth_ext_auth/auth.js /auth.js
RUN chmod +x /auth.js
COPY auth_config.yml /config/auth_config.yml
COPY ./dummy_certs /dummy_certs
RUN apk add --update nodejs