version: "3.7"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  consul1:
    environment:
      CONSUL_BIND_INTERFACE: eth0
    image: consul:1.10.0
    networks:
      - containeros-system
    command: "agent -server --client 0.0.0.0 -datacenter=main -bootstrap-expect=3 -encrypt=NToZ3N7SjUSu3Wo3zzljo14hBFzzFR1n1HoZl7gzyko= -retry-join=consul1 -retry-join=consul2 -retry-join=consul3"

  consul2:
    environment:
      CONSUL_BIND_INTERFACE: eth0
    image: consul:1.10.0
    ports: 
      - 8500:8500
    networks:
      - containeros-system
    command: "agent -server -ui --client 0.0.0.0 -datacenter=main -bootstrap-expect=3 -encrypt=NToZ3N7SjUSu3Wo3zzljo14hBFzzFR1n1HoZl7gzyko= -retry-join=consul1 -retry-join=consul2 -retry-join=consul3"

  consul3:
    environment:
      CONSUL_BIND_INTERFACE: eth0
    image: consul:1.10.0
    networks:
      - containeros-system
    command: "agent -server --client 0.0.0.0 -datacenter=main -bootstrap-expect=3 -encrypt=NToZ3N7SjUSu3Wo3zzljo14hBFzzFR1n1HoZl7gzyko= -retry-join=consul1 -retry-join=consul2 -retry-join=consul3"

networks:
  containeros-system:
  caddy:
    external: true

volumes:
  caddy_data: {}