# builder
FROM node:16-alpine

RUN npm i ts-node -g

WORKDIR /app
COPY ./src/package*.json ./

COPY ./sdk /sdk
RUN cd /sdk && npm run build && cd /app

RUN npm install

COPY ./src .

EXPOSE 8000

CMD [ "ts-node", "index.ts" ]

