# builder
FROM node:16-alpine AS typescript-builder

WORKDIR /app
COPY ./package*.json ./

RUN npm install

COPY . .

RUN npm run build

# main container
FROM node:16-alpine
ENV NODE_ENV production

RUN apk add docker

WORKDIR /app
COPY ./package*.json ./
RUN npm ci --only=prod
COPY ./installer /installer
COPY --from=typescript-builder ./app/build .

CMD [ "node", "installer/index.js" ]

